apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: drone-server
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: drone-server
    spec:
      containers:
        - image: drone/drone:0.5
          imagePullPolicy: Always
          name: drone-server
          env:
            - name: DRONE_SERVER_ADDR
              value: ":8000"
            - name: I_UNDERSTAND_I_AM_USING_AN_UNSTABLE_VERSION
              value: "true"
            - name: I_AGREE_TO_FIX_BUGS_AND_NOT_FILE_BUGS
              value: "true"

            - name: DRONE_DEBUG
              valueFrom:
                configMapKeyRef:
                  name: drone-config
                  key: server.debug.is.enabled
            - name: DRONE_SECRET
              valueFrom:
                secretKeyRef:
                  name: drone-secrets
                  key: server.secret

            - name: DRONE_DATABASE_DRIVER
              valueFrom:
                configMapKeyRef:
                  name: drone-config
                  key: server.database.driver
            - name: DRONE_DATABASE_DATASOURCE
              valueFrom:
                configMapKeyRef:
                  name: drone-config
                  key: server.database.config

            - name: DRONE_OPEN
              valueFrom:
                configMapKeyRef:
                  name: drone-config
                  key: server.is.open
            - name: DRONE_ORGS
              valueFrom:
                configMapKeyRef:
                  name: drone-config
                  key: server.orgs.list
            - name: DRONE_ADMIN
              valueFrom:
                configMapKeyRef:
                  name: drone-config
                  key: server.admin.list
            - name: DRONE_ADMIN_ALL
              valueFrom:
                configMapKeyRef:
                  name: drone-config
                  key: server.admin.everyone.is.admin

            - name: DRONE_GOGS
              valueFrom:
                configMapKeyRef:
                  name: drone-config
                  key: server.remote.gogs.is.enabled
            - name: DRONE_GOGS_URL
              valueFrom:
                configMapKeyRef:
                  name: drone-config
                  key: server.remote.gogs.url
          ports:
            - containerPort: 8000
              protocol: TCP
          resources:
            requests:
              cpu: 40m
              memory: 32Mi
          volumeMounts:
          - mountPath: /var/lib/drone
            name: db-volume
      volumes:
      - name: db-volume
        hostPath:
          # directory location on host
          path: /var/tmp/drone
